__author__ = 'Zakaria'

SUBWINDOW_SIZE = 10
HEARTBEAT_INTERVAL = 100
CHECK_INTERVAL = 120
MINIMUM_NODES = 1

SOURCE_HOST = '127.0.0.1'
SOURCE_PORT = 12344

DATATYPE_R_STREAM = 'R'
DATATYPE_S_STREAM = 'S'
DATATYPE_JOIN = 'X'
DATATYPE_HEARTBEAT = 'H'
DATATYPE_SUBWINDOW_SIZE = 'W'
DATATYPE_DELETE = 'D'
DATATYPE_PROTOCOL = 'P'


PUNCTUATION = '*'

INPUT_EXIT = "exit"
INPUT_START_STREAM = "stream"
INPUT_ADD_NODE = "addnode"
INPUT_STORE_PROTOCOL = "singleprotocol"
INPUT_STORE_PROTOCOL_INIT = "initprotocol"


SIGNAL_START_STREAM = "stream"
SIGNAL_ADD_NODE = "addnode"
SIGNAL_STORE_PROTOCOL = "singleprotocol"
SIGNAL_STORE_PROTOCOL_INIT = "initprotocol"

