__author__ = 'Zakaria'

WINDOW_SIZE = 100
DATATYPE_R_STREAM = 'R'
DATATYPE_S_STREAM = 'S'
DATATYPE_JOIN = 'X'
DATATYPE_HEARTBEAT = 'H'
DATATYPE_CONFIG = 'C'
HEARTBEAT_INTERVAL = 10
CHECK_INTERVAL = 12
MINIMUM_NODES = 1
PUNCTUATION = '*'