__author__ = 'Zakaria'

MODE_TIME = "time"
MODE_COUNT = "count"
parameter_mode = MODE_COUNT

SUBWINDOW_DEFAULT_TIME = 5000    # millisecond
SUBWINDOW_DEFAULT_SIZE = 0

COST_FUNCTION_DEFAULT_PARAM = 10
HEARTBEAT_INTERVAL = 10  # second
CHECK_INTERVAL = 15
MINIMUM_NODES = 1
PUNCTUATION = '*'

MODE_ADD_NODE_DEFAULT = "default"
MODE_ADD_NODE_PENDING = "pending"

SOURCE_HOST = '127.0.0.1'
SOURCE_PORT = 12344


DATATYPE_R_STREAM = 'R'
DATATYPE_S_STREAM = 'S'
DATATYPE_JOIN = 'X'
DATATYPE_HEARTBEAT = 'H'
DATATYPE_CHANGE_SUBWINDOW_SIZE = 'SW+-'
DATATYPE_DELETE = 'D'


INPUT_EXIT = "exit"

INPUT_ADD_NODE = "addnode"
SIGNAL_ADD_NODE = "addnode"

INPUT_SET_SUBWINDOW_SIZE = 'ssw'
SIGNAL_SET_SUBWINDOW_SIZE = 'ssw'
DATATYPE_SET_SUBWINDOW_SIZE = 'ssw'

INPUT_START_STREAM = "stream"
SIGNAL_START_STREAM = "stream"

INPUT_MODE = "mode"
SIGNAL_MODE = "mode"

