__author__ = 'Zakaria'

MODE_TIME = "time"
MODE_COUNT = "count"
join_mode = MODE_COUNT


SUBWINDOW_DEFAULT_SIZE = 0
SUBWINDOW_DEFAULT_TIME = 5000    # millisecond
subwindow_time = SUBWINDOW_DEFAULT_TIME

COST_FUNCTION_DEFAULT_PARAM = 10
HEARTBEAT_INTERVAL = 10  # second
CHECK_INTERVAL = 15
MINIMUM_NODES = 1

JOIN_CRITERION_INDEX = 1

PUNCTUATION = '*'

MODE_ADD_NODE_DEFAULT = "default"
MODE_ADD_NODE_PENDING = "pending"

SOURCE_HOST = '127.0.0.1'
SOURCE_PORT = 12344
MERGER_HOST = '127.0.0.1'
MERGER_PORT = 12350


DATATYPE_R_STREAM = 'R'
DATATYPE_S_STREAM = 'S'
DATATYPE_R_JOIN = 'RX'
DATATYPE_S_JOIN = 'SX'
DATATYPE_HEARTBEAT = 'H'
DATATYPE_INCREASE_SUBWINDOW_SIZE_R = 'SW+R'
DATATYPE_INCREASE_SUBWINDOW_SIZE_S = 'SW+S'
DATATYPE_DELETE_R = 'DR'
DATATYPE_DELETE_S = 'DS'
DATATYPE_NODE_SERIAL = 'NS'



INPUT_EXIT = "exit"

INPUT_ADD_NODE = "addnode"
SIGNAL_ADD_NODE = "addnode"

INPUT_SET_SUBWINDOW_SIZE = 'ssw'
SIGNAL_SET_SUBWINDOW_SIZE = 'ssw'
DATATYPE_SET_SUBWINDOW_SIZE = 'ssw'

INPUT_SET_SUBWINDOW_TIME = 'sswt'
SIGNAL_SET_SUBWINDOW_TIME = 'sswt'

INPUT_START_STREAM = "stream"
SIGNAL_START_STREAM = "stream"

INPUT_MODE = "mode"
SIGNAL_MODE = "mode"

